name: Docker Build & Push

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.geethika212 }}
        password: ${{ secrets.Arunaram@143 }}

    - name: Build and push frontend image
      run: |
        docker build -t ${{ secrets.geethika212 }}/myapp-frontend ./myapp/frontend
        docker push ${{ secrets.geethika212 }}/myapp-frontend

    - name: Build and push backend image
      run: |
        docker build -t ${{ secrets.geethika212 }}/myapp-backend ./myapp/backend
        docker push ${{ secrets.geethika212}}/myapp-backend
